# Generated by Django 4.1.5 on 2023-01-16 08:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kurs nomi')),
                ('image', models.ImageField(upload_to='images/courses/', verbose_name='Rasm')),
                ('finish', models.CharField(max_length=100, verbose_name='Kurs davomiyligi')),
                ('duration', models.CharField(max_length=100, verbose_name="Kurs necha soat o'tilishligi")),
                ('day', models.CharField(max_length=100, verbose_name="Kurs haftasiga nech kun bo'lishi")),
                ('requirement', models.CharField(max_length=100, verbose_name="O'quvchining minimall bilimi")),
                ('level', models.CharField(max_length=100, verbose_name="O'quvchi kursni tugatib qanday darajaga ega bo'lishi")),
                ('language', models.CharField(max_length=100, verbose_name="Dars qanday tilda o'tilishi")),
                ('price', models.IntegerField(default=100000, verbose_name="Kurs narxi (so'm)")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "O'quv kurs",
                'verbose_name_plural': "1-O'quv kurslari",
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='Telefoni')),
                ('subject', models.CharField(max_length=50, verbose_name='Sarlavxasi')),
                ('message', models.CharField(max_length=50, verbose_name='Xabar matni')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
            ],
            options={
                'verbose_name': 'Xabar yuborgan odam',
                'verbose_name_plural': '3-Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="O'qituvchi ismi")),
                ('science', models.CharField(max_length=50, verbose_name="O'qituvchining dars o'tish fani")),
                ('image', models.ImageField(upload_to='images/teachers/', verbose_name="O'qituvchining rasmi")),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "2-O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Qoshilish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='Telefoni')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': 'Kursga yozilish xabari',
                'verbose_name_plural': '4-Kursga yozilish xabarlari',
            },
        ),
    ]
